import Head from "next/head";
import { BsFillMoonStarsFill, BsGit, BsLinkedin } from "react-icons/bs";
import { BiLogoGmail } from "react-icons/bi";
import Image from "next/image";
import devhb from "../public/dev-hb-wave.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import design from "../public/design.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hemant's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          {/* Header Section */}
          <nav className="py-10 flex justify-between items-center dark:text-white">
            <h1 className="text-xl font-burtons lowercase">developedByHB</h1>
            <ul className="flex  items-center">
              <li>
                <BsFillMoonStarsFill
                  className="text-xl cursor-pointer"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-400 to-teal-400 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* Hero Section */}
          <div className="text-center p-10 lg:mt-12 lg:flex  lg:p-0 lg:items-center lg:justify-center">
            <div>
              <h2 className="text-4xl font-medium text-teal-600 py-2 md:text-5xl dark:text-teal-400">
                Hemant Bhatia
              </h2>
              <h3 className="text-xl  py-2 md:text-2xl dark:text-white">Frontend Developer</h3>
              <p className="text-medium text-gray-600 dark:text-gray-200 leading-8 py-4 max-w-2xl mx-auto md:text-lg ">
                An adaptable self learning professional who specializes in
                building scalable and performant web applications, writing
                efficient, modularized and comprehensible code and building
                highly responsive and elegant UI.
              </p>
              <div className="flex gap-16 justify-center text-4xl items-center py-3 text-gray-600 dark:text-gray-400">
                <BsLinkedin />
                <BsGit />
                <BiLogoGmail className="text-5xl" />
              </div>
            </div>
            <div className="relative mx-auto w-80 h-80 mt-20 bg-gradient-to-b overflow-hidden from-teal-500 rounded-full lg:mt-0 shrink-0">
              <Image src={devhb} layout="fill" objectFit="cover" />
            </div>
          </div>

          {/* Projects */}
          <section className="lg:mt-12">
            <div>
              <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                An epitome of the skills I posess. Include a few work and
                personal projects.
              </p>
            </div>

            <div className="md:flex md:gap-8 lg:gap-10">
              {/* cards  */}
              <div className="flex-1 text-center shadow-lg rounded-xl p-10 my-10 dark:text-white dark:shadow-gray-400 dark:shadow-md">
                <div className="flex justify-center">
                  <Image src={design} width={100} height={100} alt="project" />
                </div>
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant desings suited for your needs
                </p>
                <h4 className="text-teal-400 py-4">Tools I use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-400">Tailwind-css</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">Nextjs</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">React</p>
              </div>

              <div className="flex-1 text-center shadow-lg rounded-xl p-10 my-10 dark:text-white dark:shadow-gray-400 dark:shadow-md">
                <div className="flex justify-center">
                  <Image src={code} width={100} height={100} alt="project" />
                </div>
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant desings suited for your needs
                </p>
                <h4 className="text-teal-400 py-4">Tools I use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-400">Tailwind-css</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">Nextjs</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">React</p>
              </div>

              <div className="flex-1 text-center shadow-lg rounded-xl p-10 my-10 dark:text-white dark:shadow-gray-400 dark:shadow-md">
                <div className="flex justify-center">
                  <Image
                    src={consulting}
                    width={100}
                    height={100}
                    alt="project"
                  />
                </div>
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant desings suited for your needs
                </p>
                <h4 className="text-teal-400 py-4">Tools I use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-400">Tailwind-css</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">Nextjs</p>
                <p className="text-gray-800 py-1 dark:text-gray-400">React</p>
              </div>
            </div>
          </section>
        </section>
      </main>
    </div>
  );
}
